name: Publish release

on:
  release:
    types: [ published ]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup timezone
        run: |
          sudo timedatectl set-timezone Europe/Zurich
          timedatectl

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64
          cache: 'gradle'
          check-latest: true

      - name: Publish artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
        # If we split on '/' and take the 3rd value,
        # we can get the release name.
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          ./gradlew -Pversion=${NEW_VERSION} publish --warn --full-stacktrace
