name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Setup timezone
        run: |
          sudo timedatectl set-timezone Europe/Zurich
          timedatectl

      - uses: actions/checkout@v3

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          labels: dependencies, gradle
          reviewers: nik-sta, itsmefox
      
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.5
